config/routes.rb
LightningMash::Application.routes.draw do
  root:to => 'users#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy"

  resources :users, :only => [:index], :path => ""

  resources :snippets do
    collection do
      get 'tag'
    end
  end

end

app/models/html_with_pygments.rb
# coding: utf-8
class HtmlWithPygments < Redcarpet::Render::HTML

  #------------#
  # block_code #
  #------------#
  # コードハイライト
  def block_code( code, language )
    Pygments.highlight( code, lexer: language, options: { encoding: 'utf-8' } )
  end

end

app/models/snippet.rb
# encoding: utf-8

class Snippet < ActiveRecord::Base
  attr_accessible :title, :fragment, :tag_list, :pin

  # tag設置
  acts_as_taggable # acts_as_taggable_on :tagsカラムをセット

  # validation-rule
  validates :title, :presence => true,
                    :length => { :maximum => 30 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # ユーザーの情報をUserテーブルに入れるメソッド
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.screen_name = auth["info"]["nickname"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :signed_in?, :show_markdown, :current_user

  private

  # ユーザがログイン状態かどうか判別するためのヘルパーメソッド
  def signed_in?
    true if session[:oauth_token]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def render_not_found
    render "public/404", :layout => false, :status => 404
  end

  # ログイン認証
  def require_login
    redirect_to("/") unless signed_in?
  end

  #---------------#
  # show_markdown #
  #---------------#
  # Markdown変換
  def show_markdown( text )
    html_render = HtmlWithPygments.new( hard_wrap: true, filter_html: true )
    markdown    = Redcarpet::Markdown.new( html_render, autolink: true, fenced_code_blocks: true, space_after_headers: true )

    return markdown.render( text )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # session情報作成
  def create
    auth = request.env["omniauth.auth"]
    session[:oauth_token] = auth.credentials.token
    session[:oauth_token_secret] = auth.credentials.secret
    session[:username] = auth.extra.access_token.params[:screen_name]
    # usersテーブルの参照
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  # twitter認証の破棄
  def destroy
    session[:oauth_token] = nil
    session[:oauth_token_secret] = nil
    session[:username] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  before_filter :require_login, :only => [:index, :show, :new, :edit]

  # /snippets
  def index
    # 日付の降順 + pinの有無 でソート
    @snippets = Snippet.order("'pin' = CASE WHEN pin = 't' THEN 0 ELSE 'pin' END").order("created_at DESC").all
    @tags = Snippet.tag_counts_on(:tags).order('count DESC')
  end

  def tag
    @snippets = Snippet.tagged_with(params[:name])
    # カウントの多い順にソート
    @tags = Snippet.tag_counts_on(:tags).order('count DESC')

    render 'index'
  end

  # /snippets/(id)
  def show
    @snippet = Snippet.find(params[:id])
  end

  # /snippet/new
  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(params[:snippet])
    if @snippet.save
      # snippet_path(/snippets)
      redirect_to snippets_path, notice: 'Created!'
    else
      # newのviewの書き直し
      render action: 'new'
    end
  end

  # snippets(id)/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  def update
    @snippet = Snippet.find(params[:id])
    if @snippet.update_attributes(params[:snippet])
      redirect_to snippets_path, notice: 'Update!'
    else
      # editのviewの書き直し
      render action: 'edit'
    end
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy
    render json: { snippet: @snippet }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :require_user, :except => :index

  def index
    if signed_in?
      redirect_to('/snippets')
    end
  end

  private

  def require_user
    # @user = User.find_by_username!(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_action_classes
    %W[#{controller_name}_controller #{action_name}_action]
  end

  # icon表示用のヘルパーメソッド
  def link_to_with_icon(icon_type, path, options = {})
    link_to path, options do
      content_tag(:i, :class => "icon-#{icon_type}") {}
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  # tagクラウド表示用
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title snipp
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body

    %header
      %h1.title
        - if signed_in?
          = link_to current_user.screen_name, :snippets
        - else
          = link_to 'snipp', root_path
      %ul.links
        - if signed_in?
          %li.link= link_to_with_icon "pencil", :new_snippet, :title => "New", "data-placement" => "bottom"
          %li.link= link_to_with_icon 'signout', '/signout', :title => "Sign Out", "data-placement" => "bottom"
        - else
          %li.link= link_to_with_icon 'signin', '/auth/twitter', :title => "Sign in with Twitter", "data-placement" => "bottom"

    .main
      = yield

    %footer
      %p= link_to "github", "https://github.com/bamtsk/snipp", :target => "_blank", :title => "snipp is an open sourced project"

app/views/snippets/_form.html.haml
.content
  .row-fluid
    .span4
      %legend Snippet
    .span1.offset6
      #tmpModal.modal.hide.fade
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h3 Template
        .modal-body
          %h5 コピペして使用して下さい
          .tooltip-demo.well
            %p.muted{:style => "margin-bottom: 0;"}
              %table.table.table-bordered
                %tbody
                  %tr
                    %td
                      %a{:href => "#", :rel => "tooltip", :title => "[リンクテキスト](URL)"} link
                    %td [bamtsk/snipp · GitHub](https://github.com/bamtsk/snipp)
                  %tr
                    %td
                      %a{:href => "#", :rel => "tooltip", :title => "一文は` `で囲む"} code
                    %td `puts value`
                  %tr
                    %td
                      %a{:href => "#", :rel => "tooltip", :title => "複数文は行頭に空白4つ"} code
                    %td
                      %p
                        &nbsp&nbsp&nbsp&nbsp def num
                        %br/
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 1.next
                        %br/
                        &nbsp&nbsp&nbsp&nbsp end
          %ul.omake
            %li #、##、###：見出し（見出し文字の下に「=====」(h1)「-----」(h2)でもいい）
            %li *ABCDEFG*：斜体
            %li **ABCDEFG**：強調
            %li 「*」「+」「-」：箇条書き（記号の直後にスペースかタブ要）
            %li 行頭に数字＋ピリオド：番号付け（記号の直後にスペースかタブ要）
            %li 箇条書き・番号付けの後ろで改行は、「行末スペース*2」でできる。レベル2は、「 - 」。
            %li >：引用
            %li ![代替テキスト](画像のURL)：画像
            %li 行末にスペース2つ：段落内での改行
            %li HTMLタグ：直接タグを書く(一部制限あり)

        .modal-footer
          %a.btn{"data-dismiss" => "modal", :href => "#"} quit

      %a{"data-toggle" => "modal", :href => "#tmpModal", title: "テンプレート"}
        %i.icon-wrench

    .span1
      #cheatSeatModal.modal.hide.fade
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h3 Cheat Sheet
        .modal-body
          = image_tag 'markdown/Markdown.png'
        .modal-footer
          %a.btn{"data-dismiss" => "modal", :href => "#"} quit

      %a{"data-toggle" => "modal", :href => "#cheatSeatModal", title: "Markdownチートシート"}
        %i.icon-book



  .row-fluid
    .span4
      = form_for(@snippet, :html => {:class => 'form-vertical'}) do |f|
        - if @snippet.errors.any?
          %ul
            - @snippet.errors.full_messages.each do |msg|
              %li{:style => "color: Red"}= msg

        .field
          = f.text_field :title, :placeholder => 'title'
        .field
          = f.text_field :tag_list, id: "tags", :placeholder => 'tag'
        .wmd-panel
          .field
            = f.text_area :fragment, class: "wmd-input", id: "wmd-input", :placeholder => "`// Write your code here`"
        .field
          = f.label :pin
          = f.check_box :pin, {}, true
        .actions
          = f.submit :class => 'btn-primary'

    .span8
      .well
        #wmd-preview.wmd-panel.wmd-preview

= javascript_include_tag "markdown/runningEditor"

app/views/snippets/edit.html.haml
= render 'form'

app/views/snippets/index.html.haml
.content
  - if notice.present?
    #notice
      %p(class="alert alert-success")= notice

  .row-fluid
    .span9
      %ul{style: "list-style:none;"}
        - @snippets.each do |snippet|
          %li{:id => "snippet_#{snippet.id}"}
            %h3= snippet.title
            %div
              - if snippet.pin
                %i.icon-magnet

              = link_to_with_icon 'share', snippet_path(snippet), :title => "Show"

              .pull-right
                = link_to_with_icon 'edit', edit_snippet_path(snippet), :title => "Edit", "data-placement" => "bottom"
                = link_to_with_icon 'trash', snippet, :confirm => 'Sure?', |
                                                      :method => :delete,  |
                                                      :remote =>  true,
                                                      :title => "Delete", "data-placement" => "bottom"

            %div
              %span.badge.badge-success= "snippet " + snippet.created_at.strftime("%Y/%m/%d")
              .pull-right
                %span.label= snippet.tag_list

            %hr/

    .span3
      .well
        = link_to '全て表示', [:snippets]
        - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
          = link_to tag.name, { :action => :tag, :name => tag.name }, :class => css_class


:javascript
  $(function() {
    setTimeout(function() {
      $('#notice').fadeOut("slow");
    }, 1000);

    // 削除処理のAjax化
    $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
      $('#snippet_'+data.snippet.id).fadeOut("slow");
    });

  });

app/views/snippets/new.html.haml
%h1 New Post

= render 'form'

= link_to 'home', snippets_path

app/views/snippets/show.html.haml
.content
  .row-fluid
    .span12
      %h2= @snippet.title
      %span.label= @snippet.tag_list
      .well= raw show_markdown( @snippet.fragment )

app/views/users/index.html.haml
.section
  .caption
    %h1 snipp
    %a.btn.btn-large.btn-info{:href => "/auth/twitter"} Get Started
.section
  %h3 snippとは
  %p
    snippはmarkdownで記述されたあなたのスニペットを溜めておくことができるバッファのようなサービスです
.section
  .row-fluid
    .span3
      %h3
        %i.icon-edit
        Markdown
      %p
        スニペットの編集にはMarkdown形式を利用し、その場でリアルタイムにHTMLに書き出されます。
        %br/
        またMarkdown書式用のカンニングペーパを用意しており、文法はそちらを参照することが出来ます。
    .span3
      %h3
        %i.icon-tags
        タグクラウド
      %p
        スニペットにはタグを付けることが出来るため、タグによる検索が可能です。
    .span3
      %h3
        %i.icon-magnet
        マグネット
      %p
        使用頻度の高いスニペットはマグネットで止めておく事で、一覧ページの最上部に表示させることが出来ます。
    .span3
      %h3
      %p